title: mykb
description: Doro's public knowledge base.
theme: jekyll-theme-cayman
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: false
include:
  - "*.md"
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
defaults:
  - scope:
      path: ""
    values:
      layout: default
